[package]
name = "weatherviz"
version = "0.1.0"
edition = "2021"

[lib]
name = "renderer"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.19.0"
raqote = "0.8.2"
reqwest = { version = "0.11", features = ["blocking"] }
#openssl = { version = "0.10", features = ["vendored"] }