[package]
name = "weatherviz"
version = "0.1.0"
edition = "2021"

[lib]
name = "weatherviz_backend"
crate-type = ["cdylib"]

[dependencies]
friedrich = "0.5.0"
pyo3 = "0.19.0"
raqote = "0.8.2"
reqwest = { version = "0.11", features = ["blocking"] }
toml = "0.7.5"
