max_opacity = 1.0
min_opacity = 0.0

[gradient]
0.25 = { r = 0x00, g = 0x00, b = 0xFF }
0.55 = { r = 0x00, g = 0xFF, b = 0x00 }
0.85 = { r = 0xFF, g = 0xFF, b = 0x00 }
1.00 = { r = 0xFF, g = 0x00, b = 0x00 }
